package Entidades;
// Generated 09-Feb-2020 21:59:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String usuario;
     private String email;
     private String password;
     private Date createTime;

    public Usuarios() {
    }

	
    public Usuarios(String usuario, String password) {
        this.usuario = usuario;
        this.password = password;
    }
    public Usuarios(String usuario, String email, String password, Date createTime) {
       this.usuario = usuario;
       this.email = email;
       this.password = password;
       this.createTime = createTime;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


